---
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL5Dialect

  datasource:
    url: ${CLEAR_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql

my:
  subscriptions:
    pageSize: 9

server:
  error:
    whitelabel:
      enabled: false
    path: /error
  port: ${PORT}
