---
spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/OneDrive/Documents/GitHub/neiu-cs-321/dbdata
    username: admin
    password:
    driver: org.h2.Driver

my:
  subscriptions:
    pageSize: 3
